In [4]:
import yfinance as yf
import pandas as pd

In [5]:
#yf.Ticker('TSLA').history(period='3m', interval='1m').count()
ctyptos = ["BTC-USD","ETH-USD","DOT1-USD"]
arr=[ "DIS",
"JNJ",
"NFLX",
"PLTR",
"MSFT",
"BABA",
"CL",
"LOW",
"KO",
"MMM",
"V",
"AAL",
"MA",
"AAPL",
"BRK-B",
"MCD",
"FB",
"BMY",
"T",
"VZ",
"GD",
"NVDA",
"INTC",
"HD",
"GM",
"DNNGY",
"DIOD",
"ZM",
"ROKU",
"PYPL",
"TCEHY",
"NNND.F",
"AMD",
"AMZN",
"CRM",
"GOOG",
"IBM",
"ORCL",
"PEP",
"TEAM",
"TSLA",
"WDC",
"WMT",
"XOM",
"IWDA.AS"]
sp500=["MMM","ABT","ABBV","ABMD","ACN","ATVI","ADBE","AMD","AAP","AES","AFL","A","APD","AKAM","ALK","ALB","ARE","ALXN","ALGN","ALLE","LNT","ALL","GOOGL","GOOG","MO","AMZN","AMCR","AEE","AAL","AEP","AXP","AIG","AMT","AWK","AMP","ABC","AME","AMGN","APH","ADI","ANSS","ANTM","AON","AOS","APA","AAPL","AMAT","APTV","ADM","ANET","AJG","AIZ","T","ATO","ADSK","ADP","AZO","AVB","AVY","BKR","BLL","BAC","BK","BAX","BDX","BRK.B","BBY","BIO","BIIB","BLK","BA","BKNG","BWA","BXP","BSX","BMY","AVGO","BR","BF.B","CHRW","COG","CDNS","CPB","COF","CAH","KMX","CCL","CARR","CTLT","CAT","CBOE","CBRE","CDW","CE","CNC","CNP","CERN","CF","SCHW","CHTR","CVX","CMG","CB","CHD","CI","CINF","CTAS","CSCO","C","CFG","CTXS","CLX","CME","CMS","KO","CTSH","CL","CMCSA","CMA","CAG","COP","ED","STZ","COO","CPRT","GLW","CTVA","COST","CCI","CSX","CMI","CVS","DHI","DHR","DRI","DVA","DE","DAL","XRAY","DVN","DXCM","FANG","DLR","DFS","DISCA","DISCK","DISH","DG","DLTR","D","DPZ","DOV","DOW","DTE","DUK","DRE","DD","DXC","EMN","ETN","EBAY","ECL","EIX","EW","EA","EMR","ENPH","ETR","EOG","EFX","EQIX","EQR","ESS","EL","ETSY","EVRG","ES","RE","EXC","EXPE","EXPD","EXR","XOM","FFIV","FB","FAST","FRT","FDX","FIS","FITB","FE","FRC","FISV","FLT","FLIR","FLS","FMC","F","FTNT","FTV","FBHS","FOXA","FOX","BEN","FCX","GPS","GRMN","IT","GD","GE","GIS","GM","GPC","GILD","GL","GPN","GS","GWW","HAL","HBI","HIG","HAS","HCA","PEAK","HSIC","HSY","HES","HPE","HLT","HFC","HOLX","HD","HON","HRL","HST","HWM","HPQ","HUM","HBAN","HII","IEX","IDXX","INFO","ITW","ILMN","INCY","IR","INTC","ICE","IBM","IP","IPG","IFF","INTU","ISRG","IVZ","IPGP","IQV","IRM","JKHY","J","JBHT","SJM","JNJ","JCI","JPM","JNPR","KSU","K","KEY","KEYS","KMB","KIM","KMI","KLAC","KHC","KR","LB","LHX","LH","LRCX","LW","LVS","LEG","LDOS","LEN","LLY","LNC","LIN","LYV","LKQ","LMT","L","LOW","LUMN","LYB","MTB","MRO","MPC","MKTX","MAR","MMC","MLM","MAS","MA","MKC","MXIM","MCD","MCK","MDT","MRK","MET","MTD","MGM","MCHP","MU","MSFT","MAA","MHK","TAP","MDLZ","MPWR","MNST","MCO","MS","MOS","MSI","MSCI","NDAQ","NTAP","NFLX","NWL","NEM","NWSA","NWS","NEE","NLSN","NKE","NI","NSC","NTRS","NOC","NLOK","NCLH","NOV","NRG","NUE","NVDA","NVR","ORLY","OXY","ODFL","OMC","OKE","ORCL","OTIS","PCAR","PKG","PH","PAYX","PAYC","PYPL","PNR","PBCT","PEP","PKI","PRGO","PFE","PM","PSX","PNW","PXD","PNC","POOL","PPG","PPL","PFG","PG","PGR","PLD","PRU","PEG","PSA","PHM","PVH","QRVO","PWR","QCOM","DGX","RL","RJF","RTX","O","REG","REGN","RF","RSG","RMD","RHI","ROK","ROL","ROP","ROST","RCL","SPGI","CRM","SBAC","SLB","STX","SEE","SRE","NOW","SHW","SPG","SWKS","SLG","SNA","SO","LUV","SWK","SBUX","STT","STE","SYK","SIVB","SYF","SNPS","SYY","TMUS","TROW","TTWO","TPR","TGT","TEL","TDY","TFX","TER","TSLA","TXN","TXT","TMO","TJX","TSCO","TT","TDG","TRV","TRMB","TFC","TWTR","TYL","TSN","UDR","ULTA","USB","UAA","UA","UNP","UAL","UNH","UPS","URI","UHS","UNM","VLO","VAR","VTR","VRSN","VRSK","VZ","VRTX","VFC","VIAC","VTRS","V","VNT","VNO","VMC","WRB","WAB","WMT","WBA","DIS","WM","WAT","WEC","WFC","WELL","WST","WDC","WU","WRK","WY","WHR","WMB","WLTW","WYNN","XEL","XRX","XLNX","XYL","YUM","ZBRA","ZBH","ZION","ZTS"]

In [6]:
def GetHistoricalData(tickers,period,interval):
    data = yf.download(tickers=tickers,period=period,interval=interval,prepos=False,threads=True)
    
    data.index.name="timest"
    #df = pd.melt(data['Close'],ignore_index=False,var_name=["Metric","Asset"])
    data['Close']
    df = pd.melt(data['Close'],ignore_index=False,var_name=["Asset"])

    df=df.dropna()
    
    df['Diff'] =0
    df['100Dollar'] =0


    
    for el in tickers:
        #print(el)
        
        if df[df['Asset']==el].empty:
            continue
            
        #foreach element, fetch last column, value
        last_val= df[df['Asset']==el].tail(1)['value'][0] #try df tail
        
        multiplier = 100/last_val

        #df[df['Asset']=='AAL']
        df.loc[df['Asset']==el, 'Diff']= df.loc[df['Asset']==el, 'value']-last_val
        df.loc[df['Asset']==el, '100Dollar']= df.loc[df['Asset']==el, 'value']*multiplier
        
    return df

In [7]:
de =  GetHistoricalData(arr,'15d','15m')
de.to_csv("historicaldata.csv")

[*********************100%***********************]  45 of 45 completed

In [312]:
de['Asset'].nunique()

42

In [35]:
#df = data['Close']
df.reset_index().melt(id_vars=['Date']).set_index(['Date', 'variable'])

df3= data.reset_index().melt(id_vars=['Date'],value_name='price')
#pd.concat([data['Close']['TEAM'], data['Close']['MCD']])
display(df3)

NameError: name 'df' is not defined

In [8]:
import pandas as pd

           variable_0 variable_1         value
Date
2021-03-10  Adj Close         KO  5.144000e+01
2021-03-11  Adj Close         KO  5.088000e+01
2021-03-10  Adj Close        MCD  2.133100e+02
2021-03-11  Adj Close        MCD  2.115700e+02
2021-03-10  Adj Close        MMM  1.845100e+02
...               ...        ...           ...
2021-03-11     Volume       MSFT  2.747226e+07
2021-03-10     Volume       NVDA  9.599800e+06
2021-03-11     Volume       NVDA  7.292122e+06
2021-03-10     Volume       TEAM  1.464300e+06
2021-03-11     Volume       TEAM  1.272924e+06

[72 rows x 3 columns]

In [ ]:
!pip install pandas --upgrade

#sim_2005_melted = pd.melt(sim_2005, id_vars=sim_2005.index.name

In [ ]:
df.reset_index()

In [ ]:
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})

df

In [ ]:

import pandas as pd


d

pd.melt(data, id_vars=['ticker'])

In [ ]:
data['Close']

In [ ]:
import yfinance as yf

msft = yf.Ticker("MSFT")

# get stock info
msft.info

# get historical market data
hist = msft.history(period="max")

# show actions (dividends, splits)
msft.actions

# show dividends
msft.dividends

# show splits
msft.splits

# show financials
msft.financials
msft.quarterly_financials

# show major holders
msft.major_holders

# show institutional holders
msft.institutional_holders

# show balance sheet
msft.balance_sheet
msft.quarterly_balance_sheet

# show cashflow
msft.cashflow
msft.quarterly_cashflow

# show earnings
msft.earnings
msft.quarterly_earnings

# show sustainability
msft.sustainability

# show analysts recommendations
msft.recommendations

# show next event (earnings, etc)
msft.calendar

# show ISIN code - *experimental*
# ISIN = International Securities Identification Number
msft.isin

# show options expirations
msft.options

# get option chain for specific expiration
opt = msft.option_chain('YYYY-MM-DD')
# data available via: opt.calls, opt.puts

In [326]:
#!pip install Historic_Crypto 
#https://github.com/guptarohit/cryptoCMD
!pip install cryptocmd

Collecting cryptocmd
  Downloading https://files.pythonhosted.org/packages/af/56/71eb597dbbb7ea25034e6535da6be3086a31c898c1945bf4c1fd05227183/cryptocmd-0.6.0-py3-none-any.whl
Collecting tablib (from cryptocmd)

WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

  Downloading https://files.pythonhosted.org/packages/16/85/078fc037b15aa1120d6a0287ec9d092d93d632ab01a0e7a3e69b4733da5e/tablib-3.0.0-py3-none-any.whl (47kB)
Requirement already satisfied: requests in d:\libraries\python3.7.6\lib\site-packages (from cryptocmd) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\libraries\python3.7.6\lib\site-packages (from requests->cryptocmd) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in d:\libraries\python3.7.6\lib\site-packages (from requests->cryptocmd) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\libraries\python3.7.6\lib\site-packages (from requests->cryptocmd) (1.25.10)
Requirement already satisfied: chardet<5,>=3.0.2 in d:\libraries\python3.7.6\lib\site-packages (from requests->cryptocmd) (3.0.4)
Installing collected packages: tablib, cryptocmd
Successfully installed cryptocmd-0.6.0 tablib-3.0.0

Connected to the CoinBase Pro API.

In [329]:
from cryptocmd import CmcScraper

# initialise scraper without time interval
scraper = CmcScraper("BTC")

# get raw data as list of list
headers, data = scraper.get_data()

# get data in a json format
xrp_json_data = scraper.get_data("json")

# export the data as csv file, you can also pass optional `name` parameter
scraper.export("csv", name="xrp_all_time")

# Pandas dataFrame for the same data
df = scraper.get_dataframe()

In [330]:
df

,Date,Open,High,Low,Close,Volume,Market Cap
0,2021-03-12,57821.218747,57996.619490,55376.650088,57332.088964,5.568994e+10,1.069366e+12
1,2021-03-11,55963.180089,58091.062703,54484.593089,57805.123019,5.677234e+10,1.078136e+12
2,2021-03-10,54824.011199,57258.254976,53290.891169,56008.549401,5.729558e+10,1.044580e+12
3,2021-03-09,52272.969782,54824.117811,51981.831312,54824.117811,5.091223e+10,1.022440e+12
4,2021-03-08,51174.116947,52314.068801,49506.053458,52246.522310,4.859743e+10,9.743219e+11
...,...,...,...,...,...,...,...
2871,2013-05-02,116.379997,125.599998,92.281898,105.209999,0.000000e+00,1.168517e+09
2872,2013-05-01,139.000000,139.889999,107.720001,116.989998,0.000000e+00,1.298955e+09
2873,2013-04-30,144.000000,146.929993,134.050003,139.000000,0.000000e+00,1.542813e+09
2874,2013-04-29,134.444000,147.488007,134.000000,144.539993,0.000000e+00,1.603769e+09
2875,2013-04-28,135.300003,135.979996,132.100006,134.210007,0.000000e+00,1.488567e+09